### ISSUE TITLE
moving to csi-1.0

### ISSUE THREAD

**Issue by okartau** [intel/pmem-CSI#173]
ATM we don't have PR open, dev. is active under @avalluri fork in branch csi-1.0+cache, so I create this issue to track and comment.

I tried current state of csi-1.0+cache.
Test cluster deployment works OK (make start). CLR version I used was 27800.
test_e2e runs and shows 3 failures (31 Passed | 3 Failed | 0 Pending | 26 Skipped).
At least one new error log/failure pattern seems to be: (many instances in test output):
`desc = Volume cannot be published on requested node %shost-1`
which is reported form mastercontrollerserver.go:290.
Note the error string formatting, %s is extra and does not help

**Comment by avalluri** [comment]
@okartau I fixed the test failures and the typo(%s) in log message you pointed. Can you please check if it works for you.

**Comment by okartau** [comment]
`make test_e2e` passes without errors now, I tried twice. clear=27880 kubernetes=1.13.3

**Comment by pohly** [comment]
@avalluri it looks like you are removing support for CSI 0.3, is that right?

I think the agreement was to support both, because some users of pmem-csi might still be on Kubernetes < 1.13. This is doable, by treating the CSI interface implementation as a small wrapper around the actual driver implementation. See https://github.com/intel/oim/commit/e8c97ada3cfa29abf0ede3c1f9fe1eefb0932a16

**Comment by avalluri** [comment]
@pohly My idea is to support csi-0.0.3 as a branch, and continue devel with csi1.0.

**Comment by pohly** [comment]
Amarnath Valluri <notifications@github.com> writes:
> @pohly My idea is to support csi-0.0.3 as a branch, and continue devel
> with csi1.0.

Do you intend to freeze the old code or backport all new features into
it? If you intend to backport, then my concern is that this will be more
work on an on-going basis than setting up the code once so that it
supports both in the same code base.

**Comment by avalluri** [comment]
I will backport current state to csi-0.0.3 and cherry-pick the fixes which really work on csi-0.0.3.  I would prefer to freeze that branch as soon as possible instead of  carrying it forward, as csi-1.0 is already in GA in K8s-1.13.

**Comment by okartau** [comment]
all done here and can close this issue, or is there still something to track about 0.3.0 vs 1.0.0 support?

**Comment by avalluri** [comment]
As of my knowledge we can close this issue, as the driver now works on csi-1.0.0.
