### ISSUE TITLE
document support for interleaving DIMMs

### ISSUE THREAD

**Issue by pohly** [intel/pmem-CSI#217]
When combining multiple DIMMs, interleaved (hardware memory controller striped) access may be faster. We need to document that:
* the PMEM-CSI does not need to deal with interleaving
* how an admin can enable interleaving

**Comment by okartau** [comment]
I also 2nd that question, what can we do in this driver? The driver scope has been defined so that it operates on top of libndctl-provided abstraction presenting Buses and Regions.
The driver does not deal with DIMMs configuration. Regions are expected to be set up (using ipmctl) before this driver starts. This we have stated in README.
With scope defined like this, the driver operation can be  transparent on non-interleaved or interleaved DIMMs case, right? 
NUMA-locality needs to be taken account outside of driver when configuring interleave sets (ipmctl). The driver, while operating in LVM mode, needs to take care that it preserves NUMA-locality and does not mix different Regions into same Volume Group (handled correctly now).

**Comment by okartau** [comment]
Using interleaved DIMMS could help with driver design if it could avoid fragmentation of the space, but AFAIK, that's not the case (or can it?)

**Comment by pohly** [comment]
I'm fine with letting a cluster admin set this up before installing the driver.

Our documentation has nothing about this topic, which means that users have to figure it out for themselves. Let's use this issue to track that we need to extend our documentation (see also #214).

**Comment by pohly** [comment]
> Why would we want the driver to comprehend striping?

NUMA awareness (issue #6) may depend on it.

**Comment by okartau** [comment]
> Our documentation has nothing about this topic

We have two sentences under "Hardware required" in README, so it's more than nothing. But sure, we can add more. Or did you mean strictly "interleave" topic with "nothing"

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> Or did you mean strictly "interleave" topic with "nothing"

That.

**Comment by okartau** [comment]
Can we please modify title so that it states what is issue.
Also, can we modify first entry which now leaves impression there is some bug or missing functionality in code.
In reality PMEM-CSI driver supports interleaving and non-interleaving equally well as this aspect is transparent, driver can't know the difference.
This issue asks for more documentation (I will add label).
To improve the docs, we can explain the relation of Regions and DIMMs (perhaps showing that on diagrams?), and what impact interleaving has for Region size.
