### ISSUE TITLE
ClearLinux version should be specified for the docker image

### ISSUE THREAD

**Issue by kiendinh** [intel/pmem-csi#285]
The docker image has been changed to ClearLinux. However, later steps in the build use "swupd update", which try to update the image to the latest version. This is not only inefficient but also may introduce unnecessary instability. Since Clear Linux repository servers are slow, it may take twenty minutes just to download all packages for updating. Besides, Clear Linux itself sometimes contains unexpected changes that can have deprecations or bugs. I would suggest to specify a "known-to-work" version of the Clear Linux instead of using the latest one.

**Comment by pohly** [comment]
We have to use the latest Clear Linux, including all updates, when building a new image. Otherwise we build an image that may lack bug fixes. Manually tracking which Clear Linux release has no known bugs isn't feasible.

Yes, it may also have regressions. That's something that will have to be detected when testing that new image before promoting the image as the next image to be used in production.

Right now we don't have any of that, though, and just always build "the latest".

**Comment by okartau** [comment]
Same approach was discussed recently in connection to strategy selection for building published images.

**Comment by pohly** [comment]
PMEM-CSI releases use a fixed version of the Clear Linux base.

**Comment by kiendinh** [comment]
Thank you @pohly
