### ISSUE TITLE
check for leftover volumes during testing

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#286]
We had a regression in csi-sanity where it failed to delete volumes. It would be good to automatically check that each test leaves all nodes in the same state as before.

This could be done with a BeforeEach/AfterEach. However, we don't want to run expensive checks for tests that get skipped, so this might not be the best approach.

**Comment by okartau** [comment]
There seems to be a method that runs  CleanupAction once after all tests, so it seems like good candidate to insert such check. We get this printed at the end of e2e test report:
`INFO: Running AfterSuite actions on all node`
Seems it requires attaching a cleanup handler using AddCleanupAction (which we currently don't do).
Will it really run this handler on all nodes then? I will try to activate this feature.
What makes this checking more complex is that we need to check it differently in two modes, LVM vs Direct. TEST_XYZ variable carries that information, but only on the node running make, and no such context exists on cluster nodes, right. So we have to detect the mode somehow when checking. LV commands seem to fail in Direct mode so that will be one method to find out about mode.

**Comment by pohly** [comment]
The downside of hooking into the test suite cleanup (regardless how it's done) is that once the check triggers, finding the faulty test case is going to be lot of trial-and-error. Depending on how fast such a check runs, running it for each test case may be better. Then when it fails, it can do so via a Gomega assertion and test which leaks a volume will be marked as failed.

This can be done for csi-sanity with `BeforeEach/AfterEach` here: https://github.com/intel/pmem-CSI/blob/0d0f7f8e2823b2149d39802df316e783e30c1c11/test/e2e/storage/sanity.go#L53-L119

For E2E tests, you can add new `BeforeEach/AfterEach` into this `Context`: https://github.com/intel/pmem-CSI/blob/0d0f7f8e2823b2149d39802df316e783e30c1c11/test/e2e/storage/csi_volumes.go#L92-L94

> TEST_XYZ variable carries that information, but only on the node running make, and no such context exists on cluster nodes, right.

There's no test code that gets spawned on cluster nodes. All tests run on the build host and have the same parameters, so this shouldn't be a problem.

**Comment by okartau** [comment]
> There's no test code that gets spawned on cluster nodes

Is this mention of "runs everywhere" in test/e2e/e2e.go incorrect then?
```
// Similar to SynchornizedBeforeSuite, we want to run some operations only once (such as collecting cluster logs).
// Here, the order of functions is reversed; first, the function which runs everywhere,
// and then the function that only runs on the first Ginkgo node.
var _ = ginkgo.SynchronizedAfterSuite(func() {
        // Run on all Ginkgo nodes
        framework.Logf("Running AfterSuite actions on all node")
        framework.RunCleanupActions()
}, func() {
        // Run only Ginkgo on node 1
})
```
