### ISSUE TITLE
NodeStageVolume violates CSI spec idempotency req.

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#386]
I was going through older TODO/FIXME set, and spotted that NodeStageVolume does not
fulfill spec if Stage is asked for volume which is already mounted.
Spec requires to return 0 if that Volume is already mounted on required point (idempotency).
But our current implementation does not check for existing mount, but let's mount attempt to fail,
so we will return error.
We should make this closer to spec.
Sanity test seems not to cover repeated StageVolume.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:

> I was going through older TODO/FIXME set, and spotted that NodeStageVolume does not
> fulfill spec if Stage is asked for volume which is already mounted.
> Spec requires to return 0 if that Volume is already mounted on required point (idempotency).
> But our current implementation does not check for existing mount, but let's mount attempt to fail,
> so we will return error.
> We should make this closer to spec.

True.

> Sanity test seems not to cover repeated StageVolume.

Idempotency in general seems to be covered by poorly by the sanity test
suite. Before fixing our issue, it would be good to add such a test for
all functions to the sanity test suite. Then we'll know that the test
works (because our driver will fail initially) and we know once the fix
works (when the test passes).

**Comment by okartau** [comment]
> it would be good to add such a test

#393 is first step on that path, it adds repeated `node stage volume` and demonstrates (expected) failure when testing current code in devel

**Comment by okartau** [comment]
I think recently merged #463 covered that issue. Possible follow-up improvements to be tracked in #483
