### ISSUE TITLE
huge pages

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#498]
https://nvdimm.wiki.kernel.org/2mib_fs_dax explains how memory mapping a file on a dax-capable filesystem can be done with huge pages (2MiB) instead of the normal 4KiB.

We should write a test that verifies whether an application can use huge pages. The Wiki has instructions for testing this.

This test might currently fail, because the Wiki mentions a "-E stride=512" option for mkfs.ext4 and some other changes for xfs which we currently don't use. We might have to add that.

**Comment by pohly** [comment]
The test can be an extension of the existing https://github.com/intel/pmem-csi/blob/devel/test/e2e/storage/dax/dax.go

**Comment by okartau** [comment]
I tried the steps (no k8s involved, just command line for starter) from above-mentioned page in a VM we use for CI tests (running Clear) , but I see no traces in `/sys/kernel/debug/tracing/trace`. I wonder is that trace supposed to appear in VM. If no trace on VM, then it's not easy to use that technique in CI tests.
Next, I will try on bare metal for comparison.
Another side question is, what determines the page size for given region: is there some setting (to be set where?), or is this supposed to be transparent to user? Or is it so that bigger page is tried first with fallback to smaller size?

**Comment by pohly** [comment]
I don't know. Please ask our Intel colleagues who work on the kernel support for PMEM.

**Comment by pohly** [comment]
Resolved via https://github.com/intel/pmem-csi/pull/499
