### ISSUE TITLE
Clear Linux: node registration stuck

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#555]
I just ran local E2E testing on latest Clear Linux (cluster and container image) and observed that bringing up PMEM-CSI got stuck because one out of three nodes failed to register itself:
```
I0326 10:21:35.853359       1 pmem-csi-driver.go:482] Failed to register: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.104.207.128:10000: i/o timeout", retrying after 10 seconds...
I0326 10:21:45.853504       1 pmem-csi-driver.go:477] Registering controller...
```

The other nodes were successful with that same address (after one failed attempt):
```
I0326 10:12:16.594333       1 pmem-csi-driver.go:482] Failed to register: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.104.207.128:10000: connect: connection refused", retrying after 10 seconds...
I0326 10:12:26.594723       1 pmem-csi-driver.go:477] Registering controller...
I0326 10:12:26.600413       1 grpc.go:134] VerifyPeerCertificate: CN=pmem-registry
I0326 10:12:26.602616       1 tracing.go:19] GRPC call: /csi.v1.Controller/ListVolumes
I0326 10:12:26.602635       1 tracing.go:20] GRPC request: {}
I0326 10:12:26.605626       1 controllerserver-node.go:337] ListVolumes
I0326 10:12:26.605640       1 tracing.go:25] GRPC response: {}
I0326 10:12:26.608769       1 pmem-csi-driver.go:488] Registration success
```

Networking really was broken, curl couldn't connect either. The network plugin on Clear is flannel.

**Comment by okartau** [comment]
Now that pmem-csi-periodic reaches Clear stage after recent state-save fix, it can be observed that set of tests often fails, and the reason seems to be similar, one node fails to join  the cluster. The root cause is same as here?

**Comment by pohly** [comment]
@okartau : in your observations, is it limited to Clear or does it also occur on Fedora?

Depending on that, perhaps changing the CNI plugin to the one which works more reliably may help? I tried to use Weaveworks also on Clear, but couldn't get it to work and gave up at that time.

**Comment by okartau** [comment]
> is it limited to Clear or does it also occur on Fedora?

That is limited to Clear.
I can try "weave on clear" on a local instance where it's easier to debug.

**Comment by okartau** [comment]
Some debug notes on Clear system, flannel used as CNI. This was made after I tried to change 1_17 to 1_16 to see does it make any difference. It did not. Testing goes on for a while, then at some point, one driver pod can not register. What I observed:
"Bad" driver pod runs at same node where controller pod: worker1. This I checked in 2 occasions so I believe it's not coincidence.
Driver pods on worker2 (also, worker3) were good, so I compared worker1 and worker2.
- worker2 (OK state): inside pod container, there is TCP socket to cluster_addr:10000 in ESTAB state
- worker1 (bad state): inside pod container, there is TCP socket to cluster_addr:10000 in SYN-SENT state.

This socket, and routing table (similar to worker2) display in names-resolved fashion indicates that DNS is not to blame: worker1 can resolve names OK, and knows cluster addr by number.
I compared iptables entries worker1 vs worker2. The table entries are same/similar, but whole block of KUBE-SERVICES had zero counts on worker1, like no packets ever hit this chain.
I installed network-related tools (brctl, arp, tcpdump).
Note that worker1 had two vethXXX interfaces in bridge cni0, one related to pmem-csi-node, another to pmem-csi-controller (worker2 only has one, for it's node).
I checked with tcpdump, what "src or dst cluster_addr" packets move on bridge interfaces. On a node-related interface, there were SYN packets sent to cluster_addr:10000, without reply. The destination MAC was addr of cni0 interface. On controller-related bridge interface, no cluster_ip packets were seen. Seems, packets do not reach the incoming bridge interface of controller ?

**Comment by okartau** [comment]
Next step, captured packets on cni0 interface. This is what happens in broken state:
1. node pod 10.244.3.17 sends out SYN pkt to cluster addr 10.107.53.118, this gets sent to cni0 interface MAC addr.
2. same SYN packet is resent from cni0 MAC with dst IP changed to controller pod addr 10.244.3.16.
3. controller pod responds with SYN ACK, sending _directly_ to src IP which is node pod address.
4. node pod sends TCP RST to controller pod, seems it dislikes the packet coming from different peer.

The NAT is applied by cni0 interface but only in one way, because return packet has dst addr on same subnet and is sent directly.
For pods on remote nodes, all gets sent to cni0, since dst is not local, i.e. there the NAT is applied in both directions.

The next question, how the local node TCP can work while the system is still in good shape? I will try to capture some trace from that as well.

**Comment by okartau** [comment]
Captured packets on cni0 in working state. The testing started with controller pod on worker2 this time.
1. node pod 10.244.3.3 sends SYN pkt to controller pod addr 10.244.3.2
2. replica of that packet appears, sent from cni0 MAC address, otherwise identical.
3. controller pod sends SYN ACK to node pod based on 1st packet
4. controller pod sends another SYN ACK (duplicate) to node pod based on replica SYN packet.

There is extra traffic on line with many duplicates sent, but TCP session is kept open.
It does not look pretty with many DUP packets but it appears to work.
Seems, cni0 attempt to act as middle-man also happens, but 1st pkt already has controller local address so NAT did not really change IP addresses, only adds 2nd stream of packets coming from another MAC address. 
Crucial part is that 1st SYN goes out with dst IP set as controller own address, not cluster address this time. So even if cni0 packet would reach first, it would still work as IP addresses are correct (no NAT applied). This is bit strange because the socket in node container still points to cluster address. Somewhere on the way this gets swapped to node address, which makes it work.

Still, in both cases the state from TCP protocol standpoint is far from clean, as there is double streams of packets sent both ways.
Seems the bridge and/or NAT idea does not work out cleanly.

One idea, should we try to explicitly configure the CNI bridging, with some parameters described here: https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/README.md
in hope to make TCP flow cleaner ? One possibility is to assign address to cni0 bridge and make it a gateway. Would this help?

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> One idea, should we try to explicitly configure the CNI bridging, with some parameters described here: https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/README.md
> in hope to make TCP flow cleaner ? One possibility is to assign
> address to cni0 bridge and make it a gateway. Would this help?

I have no idea.

**Comment by okartau** [comment]
after long series of failures, pmem-csi-periodic had one OK run, means recent change running Controller separately (or combined with some other recent change?) really helped Clear testing to pass.

**Comment by pohly** [comment]
Olev Kartau <notifications@github.com> writes:
> recent change running Controller separately (or combined with some
> other recent change?) really helped Clear testing to pass

We can be pretty sure that it was that and nothing else, because I
incrementally added changes and that was the one which fixed the
failures on Clear.

**Comment by pohly** [comment]
@okartau: please create that upstream Clear Linux issue and then close this one here.

**Comment by pohly** [comment]
https://github.com/clearlinux/distribution/issues/1980Moved over to Clear Linux in
