### ISSUE TITLE
"stores state across reboots" failure in pmem-csi-periodic job 581

### ISSUE THREAD

**Issue by okartau** [intel/pmem-csi#569]
Starting on Apr-2nd, pass rate of pmem-csi-periodic went down again.
In job 581 there is failure where volumes state after reboot did not match:

https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi-periodic/581/testReport/junit/fedora-1_15.direct-testing/sanity/PMEM_CSI_stores_state_across_reboots_for_single_volume/

I compared Expected list to "to consist" (needs re-arrange of blocks as these are shown in different order, plus re-arrange of name vs size order in some places, and diff in ignore-whitespace style).
Here is the actual diff:
Expected:
```
VolumeId: "state--da663aa8543a457c07dfc0f0513aa9a660e5222f38c5898d5993508b",
VolumeContext: {
    "name": "state-volume-58EDBE6F-6B898A05",
    "size": "115343360",
},
```

To consist:
```
VolumeId: "state--da663aa8543a457c07dfc0f0513aa9a660e5222f38c5898d5993508b",
VolumeContext: {
    "name": "state-volume-58EDBE6F-6B898A05",
},
```

Seems "to consist" side lacks the "size" attribute in VolumeContext.
Why this started to fail recently?
Related to recent e2e testing changes?

There is another same-titled failure in lvm test, I haven't looked yet into details there.

**Comment by okartau** [comment]
Another side-track to think here, why do we have entries in state that may have size attribute in map, or may not have. Is this known and planned, or does it point to another potential/real issue.

**Comment by pohly** [comment]
> Can that possibly happen because we re-use nodeVolume here for different state entries, without clearing it in between?

Your probably nailed it. The question remains why this occurs now.

`GetAll` has to clear the variable first before reading into it with `json.Decode` because `Decode` adds values without removing existing ones, but `GetAll` doesn't clear: https://github.com/intel/pmem-csi/blob/d03cf74be569b333e274c2aaee5f732c0b49d45d/pkg/pmem-state/pmem-state.go#L110-L137

@avalluri: is there a reason why state manager was written with `interface{}` as type in the API? If the purpose was to allow storing different structs, then that doesn't work because `GetAll` assumes that all entries fit into the same struct.

Making it generic also doesn't help us, we only need it for nodeVolume. Unless you have a very simple way of clearing that variable in a generic way, then let's just get rid of `interface{}`.

**Comment by okartau** [comment]
> The question remains why this occurs now.

The error state is reached if there are other volumes, which are in practice left-overs from previous tests, (easy to trace back in log to see where those were created). It is possible that earlier we did not have leftover volumes present during this test?
BTW, do we have policy that each test should clean up after it has completed? 
With other volumes present, it can run OK in case of "lucky" order of restored volumes.

**Comment by pohly** [comment]
> which are in practice left-overs from previous tests, (easy to trace back in log to see where those were created). It is possible that earlier we did not have leftover volumes present during this test?

Possible, but that's a bug then.

> BTW, do we have policy that each test should clean up after it has completed?

Yes. You yourself added such a check. Does it not trigger or does it not cover the test that leaked a volume?

https://github.com/intel/pmem-csi/blob/d03cf74be569b333e274c2aaee5f732c0b49d45d/test/e2e/storage/sanity.go#L1063-L1067

**Comment by avalluri** [comment]
> @avalluri: is there a reason why state manager was written with interface{} as type in the API? If the purpose was to allow storing different structs, then that doesn't work because GetAll assumes that all entries fit into the same struct.

I would prefer to keep the `StateManager` API generic so that it could be reused, one potential case I could see in near feature is storing the operator's state though I am no clear about the specifics.

We could solve this particular issue by clearing the contents at the caller side. I just prepared a [patch](https://github.com/avalluri/pmem-CSI/commit/1df3841b6bc3a6788704c862eb2ee3161da0101e).

@olev, Could you please check if [this](https://github.com/avalluri/pmem-CSI/commit/1df3841b6bc3a6788704c862eb2ee3161da0101e) helps to fix this issue.
