### ISSUE TITLE
Features/Improvements for Operator: post v0.7.0 release

### ISSUE THREAD

**Issue by avalluri** [intel/pmem-csi#572]
- Operator shall be able to handle node reboot/pod restart, such that it should reload all the know deployments prior to restarting.
- Extend the operator E2E tests with the below cases:
  * disruptive tests to ensure that the operator could recover state after a sudden reboot
  * check the need for any tests specific to testing vs production environments

**Comment by pohly** [comment]
Instead of having one large issue with several different sub-issues, let's create separate issues and then triage whether they are needed for 0.7.0 separately.

> Operator shall be able to handle node reboot/pod restart, such that it should reload all the know deployments prior to restarting.

Part of https://github.com/intel/pmem-csi/pull/610, no need for a separate issue anymore.

> disruptive tests to ensure that the operator could recover state after a sudden reboot

https://github.com/intel/pmem-csi/issues/612

> check the need for any tests specific to testing vs production environments

I don't know what is meant here. Can you create a separate issue with more details?

**Comment by pohly** [comment]
@avalluri can this be considered resolved?

**Comment by avalluri** [comment]
> @avalluri can this be considered resolved?

I think we can close this. I could is nothing that we can test the operator itself specific to production vs testing.
