### ISSUE TITLE
update example apps

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#620]
I was discussing with Eric Ernst how to demo PMEM-CSI. He suggested running fio on volumes while I pointed out that raw file performance misses the semantic aspects of PMEM (byte addressable, like RAM). For that, we can use the https://github.com/intel/pmem-csi/blob/ee3200794a1ade49a02df6f359a134115b409e90/test/cmd/pmem-dax-check/main.go test program. We also discussed that it's currently tricky for a user to pull all of that together.

Therefore we concluded that it would be useful to:
- include pmem-dax-check (built from source) and fio (via `swupd bundle-add fio`) in the pmem-csi-driver-test image
- replace the "busybox" image with "pmem-csi-driver-test" in the example app YAML files

`hack/set-version.sh` should already lock down the image version also in the example app YAML files, but we need to test that once.

**Comment by pohly** [comment]
Updating documentation can come later, after https://github.com/intel/pmem-csi/pull/562 has been merged.

**Comment by okartau** [comment]
I think it makes sense to branch for this PR after #561 gets merged

**Comment by okartau** [comment]
To clarify do I get the current state correctly in context of proposed changes and method:
We want to add something in `BIN_SUFFIX=-test` docker image but not in production image.
In Dockerfile we have comment stating:
```
# Here we choose explicitly which binaries we want in the image and in 
# which flavor (production or testing).
```
However, I don't see actual code implementing copying different set of images (production vs. testing), instead, there is same copying code, using different value of BIN_SUFFIX, but that does not select "explicitly which binaries" as comment explains.
So does current change plan mean we need to introduce if/else block there so that we add more binaries (and run more `swupd bundle-add`) if BIN_SUFFIX=-test ?

**Comment by pohly** [comment]
> We want to add something in BIN_SUFFIX=-test docker image but not in production image.

Correct.

> So does current change plan mean we need to introduce if/else block there so that we add more binaries (and run more swupd bundle-add) if BIN_SUFFIX=-test ?

Something like that, yes. Whether it is done in the Dockerfile or in the Makefile is up to you.
