### ISSUE TITLE
markup for warnings

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#736]
It would be useful to highlight paragraphs as info or warning (as in https://github.com/github/markup/issues/887).

The proposal with embedded :bangbang: in a table was tried, but didn't work with Sphinx (`:bangbang:` as rendered literally, https://github.com/intel/pmem-csi/pull/715#discussion_r489332503):

```
### Metrics support

:bangbang: | Metric support is an alpha feature. What data is provided may change.
:---: | :---
```

=>

### Metrics support

:bangbang: | Metric support is an alpha feature. What data is provided may change.
:---: | :---

**Comment by pohly** [comment]
@intelkevinputnam : do you have an idea how to do this?

**Comment by intelkevinputnam** [comment]
I don't know of a way to make special characters work for both GitHub and Sphinx. Rather than the emoji, though, you could use `**WARNING**` or `**NOTE**`, or `**!!**`:

**!!** | Metric support is an alpha feature. What data is provided may change.
:---: | :---

restructuredText has "Admonitions" which can be warnings, notes, etc. Markdown doesn't have them out of the box, though. [Myst flavored markdown](https://myst-parser.readthedocs.io/en/latest/using/syntax.html#directives-a-block-level-extension-point) implements reST admonitions with this syntax:

````
```{admonition} Warning
This is Beta software.
```
````
In GitHub they look like this: 

```{admonition} Warning
This is Beta software.
```

I could probably implement something that works like this in a couple of days. They work OK in GitHub (the notes would appear in code blocks) and would be proper "Notes" and "Warnings" in Sphinx output.

**Comment by pohly** [comment]
I think `**WARNING**` and `**NOTE**` inside a table are good enough, no need to implement any custom syntax support in the publishing pipeline.

@avalluri : agreed?

**Comment by avalluri** [comment]
> @avalluri : agreed?

Yes.

**Comment by pohly** [comment]
This renders poorly in the docsite: https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/job/PR-760/Doc_20Site/docs/install.html#metrics-support

Let's stick with the current approach (`**WARNING:**` or `**NOTE:**` at the beginning of a paragraph.
